exports.up = function(knex) {
  return knex.schema
    .createTable('users', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.string('email').unique().notNullable()
      table.string('password').notNullable()
      table.string('first_name')
      table.string('last_name')
      table.string('role').notNullable()
      table.boolean('is_active').defaultTo(true)
      table.timestamps(true, true)
    })
    .createTable('students', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('user_id').references('id').inTable('users')
      table.string('student_number').unique()
      table.string('grade_level')
      table.string('section')
      table.date('enrollment_date')
      table.string('status').defaultTo('active')
      table.timestamps(true, true)
    })
    .createTable('teachers', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('user_id').references('id').inTable('users')
      table.string('employee_number').unique()
      table.string('specialization')
      table.date('hire_date')
      table.string('status').defaultTo('active')
      table.timestamps(true, true)
    })
    .createTable('subjects', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.string('name').notNullable()
      table.string('code').unique()
      table.string('grade_level')
      table.text('description')
      table.timestamps(true, true)
    })
    .createTable('classes', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('subject_id').references('id').inTable('subjects')
      table.uuid('teacher_id').references('id').inTable('teachers')
      table.string('grade_level')
      table.string('section')
      table.string('academic_year')
      table.timestamps(true, true)
    })
    .createTable('grades', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('student_id').references('id').inTable('students')
      table.uuid('class_id').references('id').inTable('classes')
      table.string('assessment_type')
      table.decimal('score', 5, 2)
      table.decimal('max_score', 5, 2)
      table.date('date')
      table.text('comments')
      table.timestamps(true, true)
    })
    .createTable('attendance', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('student_id').references('id').inTable('students')
      table.uuid('class_id').references('id').inTable('classes')
      table.date('date').notNullable()
      table.string('status').notNullable()
      table.text('notes')
      table.timestamps(true, true)
    })
    .createTable('payments', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('student_id').references('id').inTable('students')
      table.decimal('amount', 10, 2)
      table.date('payment_date')
      table.string('payment_method')
      table.string('status')
      table.string('reference_number')
      table.timestamps(true, true)
    })
    .createTable('schedules', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('class_id').references('id').inTable('classes')
      table.string('day_of_week')
      table.time('start_time')
      table.time('end_time')
      table.string('room')
      table.timestamps(true, true)
    })
    .createTable('messages', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('sender_id').references('id').inTable('users')
      table.uuid('receiver_id').references('id').inTable('users')
      table.string('subject')
      table.text('content')
      table.boolean('is_read').defaultTo(false)
      table.timestamps(true, true)
    })
}

exports.down = function(knex) {
  return knex.schema
    .dropTableIfExists('messages')
    .dropTableIfExists('schedules')
    .dropTableIfExists('payments')
    .dropTableIfExists('attendance')
    .dropTableIfExists('grades')
    .dropTableIfExists('classes')
    .dropTableIfExists('subjects')
    .dropTableIfExists('teachers')
    .dropTableIfExists('students')
    .dropTableIfExists('users')
}
